image:
  - Visual Studio 2019

environment:
  PATH: C:\msys64\usr\bin
  CXX: g++

install:
  - cmd: pacman -S --noconfirm parallel pcre2-devel

build:
  parallel: true

build_script:
  - cmd: bash -xe ./ci/build.sh

on_success:
  - python3 ci/appveyor_irc-notify.py mcfproj "[ lh_mouse {repo_name}#{short_commit}] passed on {branch} by {author} ({build_url})"

on_failure:
  - python3 ci/appveyor_irc-notify.py mcfproj "[ lh_mouse {repo_name}#{short_commit}] errored on {branch} by {author} ({build_url})"
