container:
  image: "ubuntu:focal"

task:
  tests_script:
    - "aptitude update"
    - "aptitude install -y autoconf automake g++ make"
    - "aptitude install -y parallel libpcre2-dev"
    - "./ci/build.sh"
    - "./check_includes.sh"
