container:
  image: ubuntu:focal

task:
  environment:
    LANG: C.UTF-8

  build_script:
    - export LANG=C.UTF-8
    - apt-get update
    - apt-get install -y autoconf automake libtool g++ make python3
    - apt-get install -y parallel libpcre2-dev
    - ./ci/build.sh
    - ./check_includes.sh
