container:
  image: ubuntu:focal

task:
  environment:
    LANG: C.UTF-8
    DEBIAN_FRONTEND: noninteractive
    CONFIGURE_HOST: x86_64-pc-linux
    CONFIGURE_OPTS: --disable-static

  build_script:
    - apt-get update
    - apt-get install -y --no-install-recommends autoconf automake libtool g++ gettext make parallel python3
    - apt-get install -y libedit-dev libpcre2-dev libssl-dev zlib1g-dev
    - ./ci/build.sh
