language: cpp

os: linux
dist: bionic

addons:
  apt:
    packages:
      - parallel
      - libpcre2-dev

compiler:
  - gcc
  - clang

script:
  - ./ci/build.sh
  - ./check_includes.sh

notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.libera.chat:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
